server:
  port: 8080

spring:
  application:
    name: assets-proxy
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/assetsdb}
    username: ${DB_USER:assets}
    password: ${DB_PASS:assets}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
  jackson:
    time-zone: UTC

management:
  endpoints:
    web:
      exposure:
        include: health,info

